DELETE FROM `command` WHERE `name`='npcbot add';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot add', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot command';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot command', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot command follow';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot command follow', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot command follow only';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot command follow only', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot command nocast';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot command nocast', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot command nogossip';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot command nogossip', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot command nolongcast';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot command nolongcast', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot command rebind';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot command rebind', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot command standstill';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot command standstill', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot command stopfully';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot command stopfully', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot command unbind';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot command unbind', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot command walk';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot command walk', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot createnew';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot createnew', 3, NULL);
DELETE FROM `command` WHERE `name`='npcbot delete';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot delete', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot delete free';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot delete free', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot delete id';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot delete id', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot distance';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot distance', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot distance attack';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot distance attack', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot distance attack long';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot distance attack long', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot distance attack short';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot distance attack short', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot dump';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot dump', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot dump load';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot dump load', 3, NULL);
DELETE FROM `command` WHERE `name`='npcbot dump write';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot dump write', 3, NULL);
DELETE FROM `command` WHERE `name`='npcbot free';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot free', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot go';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot go', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot gs';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot gs', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot hide';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot hide', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot info';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot info', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot kill';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot kill', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot list spawned';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot list spawned', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot list spawned free';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot list spawned free', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot log clear';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot log clear', 3, NULL);
DELETE FROM `command` WHERE `name`='npcbot lookup';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot lookup', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot move';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot move', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot order';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot order', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot order cast';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot order cast', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot order pull';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot order pull', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot recall';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot recall', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot recall spawns';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot recall spawns', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot recall teleport';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot recall teleport', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot reloadconfig';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot reloadconfig', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot remove';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot remove', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot revive';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot revive', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot sendto';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot sendto', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot sendto last';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot sendto last', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot sendto point';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot sendto point', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot sendto point set';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot sendto point set', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot set';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot set', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot set faction';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot set faction', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot set owner';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot set owner', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot set spec';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot set spec', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot show';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot show', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot spawn';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot spawn', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot suicide';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot suicide', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot unhide';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot unhide', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot useonbot item';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot useonbot item', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot useonbot spell';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot useonbot spell', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot vehicle';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot vehicle', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot vehicle eject';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot vehicle eject', 0, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp add';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp add', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp del';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp del', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp go';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp go', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp info';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp info', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp links';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp links', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp list';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp list', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp list all';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp list all', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp move';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp move', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp setflags';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp setflags', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp setflags z';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp setflags z', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp setlevels';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp setlevels', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp setlevels z';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp setlevels z', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp setlinks';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp setlinks', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp setname';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp setname', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp setweights';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp setweights', 2, NULL);
DELETE FROM `command` WHERE `name`='npcbot wp spawnall';
INSERT INTO `command` (`name`, `security`, `help`) VALUES ('npcbot wp spawnall', 2, NULL);
